### ISSUE TITLE
Adaptive time stepping

### ISSUE THREAD

**Issue by andrsd** [andrsd/godzilla#114]
### Use case

- compute CFL
- used that as `dt`

### Syntax

```
problem:
  type: XYZTransientProblem
  ts_adapt:
      type: XYZTSAdapt
      params
```

### Design

- Use [this PETSc TSAdapt for CFL code](https://petsc.org/main/src/ts/adapt/impls/cfl/adaptcfl.c.html#TSAdaptCreate_CFL) to write a new PETSc TSAdapt class called "godzilla".
- There should be a callback in `TransientInterface` that will be called from `TSAdaptChoose_godzilla`. It will look like:
   ```
    PetscErrorCode ts_adapt_choose(PetscReal h,PetscInt *next_sc,PetscReal *next_h,PetscBool *accept,PetscReal *wlte,PetscReal *wltea,PetscReal *wlter)
    ```
    - We will need to extract the application context from the TS object and call `ts_adapt_choose` (the usual)
- `TransientInterface` will extract `TSAdapt` from its `TS` object

### Notes

CFL time adaptation is already in PETSc, so also be able to use the schemes in PETSc. Maybe via this syntax:
```
problem:
  type: XYZTransientProblem
  ts_adapt:
    scheme: <PETSc TSAdapt scheme>
    min: <value>
    max: <value>
```
