### ISSUE TITLE
Functions

### ISSUE THREAD

**Issue by andrsd** [andrsd/godzilla#7]
Allow things like this:

```
functions:
  linipol1:
    type: LinearInterpolation
    x: [0, 1, 2, 3]
    y: [10, 5, 6, 2]
...
bcs:
  left:
    type: DirichletBC
    boundary: ...
    value: '10*linipol1(t)'
```

Wherever we expect parsed expression we should be able to use function specified via `functions` block, with their names.

## Design

1. Take muParser and modify callbacks such they take `void * ctx` as a last argument.
2. Maintain list of known functions in some container
3. Every time we build a muparser instance, register all known functions form the container with the parser (note: we will want to wrap the parser into our class, so this happens every time somebody uses the parsed capability)
4. Each function will need to specify a C callback that it will need to register with the parser

Note functions will have to be build quite early, but that should not be a problem.
